spring.application.name=EcommerceSaaS 

spring.datasource.url=jdbc:postgresql://db.dbfvmpfdnwdbzzxdnaoa.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=VanSon16101960

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#SSL cho Supabase
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

#JWT
jwt.secret=${JWT_SECRET}
JWT_SECRET = VANSON_ECOMMERCE_SAAS_JWT_SECRET_2026_ULTRA_SECURE_KEY_9x8y7z6a5b4c3d2e1f0